INSERT INTO location VALUES (1,'2138 King Court','','Santa Clara','Santa Clara','CA','in the back we have a peanut feeder, a thistle feeder, and a general purpose seed feeder','NAD-27','37.36152','121.99376');
INSERT INTO location VALUES (2,'Alviso Marina','http://santaclaracounty.org/parks/prkpages/alviso.htm','Alviso','Santa Clara','CA','the marina parking lot provides access to many miles of levees suitable for biking or walking. the open water right near the parking lot sometimes yields interesting birds.','WGS 84','37.42965','121.97839');
INSERT INTO location VALUES (3,'Andrew Molera','http://parks.ca.gov/central/monterey/amsp.htm','Monterey','Monterey','CA','you can hike in less than a mile to a campground near the beach.','mapblast','36.272734','121.842155');
INSERT INTO location VALUES (4,'Anza Borrego Desert State Park','','Borrego Springs','San Diego','CA','','','','');
INSERT INTO location VALUES (5,'Arastradero Preserve','http://www.arastradero.org/','Mountain View','Santa Clara','CA','','mapblast','37.426691','122.138925');
INSERT INTO location VALUES (6,'Arcata Marsh','http://www.arcatacityhall.org/birding.html','Arcata','Humboldt','CA','an amazing artificial marsh created by the City of Arcata to process its sewage.','','','');
INSERT INTO location VALUES (7,'Azelea State Reserve','http://parks.ca.gov/allpages/default.asp?page_id=420','McKinleyville','Humboldt','CA','a lovely park full of wild azeleas growing in forest clearings','','','');
INSERT INTO location VALUES (8,'Bend Wastewater Treatment Plant','','Bend','Deschutes','OR','Bill visited this site with Steve. Steve was checking it for a book about Oregon\'s sewage ponds.','Unknown','44.0586','121.3142');
INSERT INTO location VALUES (9,'Big Sur','http://www.bigsurcalifornia.org/','Big Sur','Monterey','CA','','','','');
INSERT INTO location VALUES (10,'Bodega Bay','','Bodega','Sonoma','CA','','','','');
INSERT INTO location VALUES (11,'Bolinas Lagoon','http://www.marin.org/mc/pos/osdboli.html','Bolinas','Marin','CA','','Unknown','37.928','122.689');
INSERT INTO location VALUES (12,'Burney Falls','http://www.burneyfalls.com/pages/burnyfls.html','Burney','Shasta','CA','','Unknown','40.9066','121.6577');
INSERT INTO location VALUES (13,'Butte Valley Wildlife Area','http://www.buttevalleychamber.com/','Macdoel','Siskiyou','CA','','Unknown','41.6701','121.8749');
INSERT INTO location VALUES (14,'Calero Reservoir','http://claraweb.co.santa-clara.ca.us/parks/prkpages/calero.htm','San Jose','Santa Clara','CA','A reservoir south of San Jose, said to be a reliable spot for Bald Eagles','mapblast','37.2016','121.82835');
INSERT INTO location VALUES (15,'Cape May','','Cape May','Cape May','NJ','','','','');
INSERT INTO location VALUES (16,'Carmel','','Carmel','Monterey','CA','','','','');
INSERT INTO location VALUES (17,'Carmel River','','Carmel','Monterey','CA','','','','');
INSERT INTO location VALUES (18,'Champaign County','','Champaign','Champaign','IL','Our ancestral home.','Unknown','40.113','88.264949');
INSERT INTO location VALUES (19,'Charleston Slough','http://www.calmanac.com/paw/paonline/things_do/baylands.shtml','Palo Alto','Santa Clara','CA','Our most visited and most productive site.','mapblast','37.461','122.115');
INSERT INTO location VALUES (20,'Chesboro Reservoir','','Morgan Hill','Santa Clara','CA','','','','');
INSERT INTO location VALUES (21,'Chez Frankel','','Big Sur','Monterey','CA','Between Gorda and Ragged Point','WGS 84','35.83825','121.39863');
INSERT INTO location VALUES (22,'China Camp State Park','','San Rafael','Marin','CA','','','','');
INSERT INTO location VALUES (23,'Cleveland National Forest','','Julian','San Diego','CA','','','','');
INSERT INTO location VALUES (24,'Clifton Court Forebay','','','Contra Costa','CA','','','','');
INSERT INTO location VALUES (25,'Coast Guard Wharf','','Monterey','Monterey','CA','','NAD-27','36.594688','121.880567');
INSERT INTO location VALUES (26,'Colusa NWR','http://www.r1.fws.gov/sacnwrc/','Colusa','Colusa','CA','','Unknown','39.2396','122.0742');
INSERT INTO location VALUES (27,'Coyote Creek County Park','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (28,'Coyote Creek Field Station','http://www.sfbbo.org/ccfs01.html','Alviso','Santa Clara','CA','Formerly the Coyote Creek Riparian Station, now part of the San Francisco Bay Bird Observatory','mapblast','37.420236','121.987878');
INSERT INTO location VALUES (29,'Coyote Hills','http://www.ebparks.org/parks/coyote.htm','Fremont','Alameda','CA','a great place for flying RC gliders. There\'s also a lovely boardwalk and some golden hills for walking on','WGS 84','37.55058','122.08602');
INSERT INTO location VALUES (30,'Coyote Point Marina','http://www.cpyc.com/','Burlinghame','San Mateo','CA','First visited here with Steve Shunk  in January 2001.','Unknown','37.567','122.3669');
INSERT INTO location VALUES (31,'Crittenden Marsh','','Mountain View','Santa Clara','CA','','','','');
INSERT INTO location VALUES (32,'Crown Memorial State Beach','http://www.parks.ca.gov/allpages/default.asp?page_id=526','Alameda','Alameda','CA','','','','');
INSERT INTO location VALUES (33,'Don Edwards Center','http://www.r1.fws.gov/sfbnwr/default.htm','Alviso','Santa Clara','CA','','WGS 84','37.43269','121.96244');
INSERT INTO location VALUES (34,'Drawbridge','http://www.slip.net/~bobk/','Fremont','Santa Clara','CA','An abandoned town along the amtrak tracks in the marshes of Fremont. We got to go there during a San Jose christmas bird count','mapblast','37.466389','121.973889');
INSERT INTO location VALUES (35,'Ed Levin State Park','http://santaclaracounty.org/parks/prkpages/levndch.htm','Milpitas','Santa Clara','CA','Lat: 37.445855 Lon: -121.857762','mapblast','37.445855','121.857762');
INSERT INTO location VALUES (36,'Elkhorn Slough','http://www.elkhornslough.org/','Santa Cruz','Monterey','CA','a lovely estuary south of Santa Cruz. Unfortunately, the slough\'s limited access hours have prevented us from exploring it in depth.','mapblast','36.804444','121.785833');
INSERT INTO location VALUES (37,'Fairhaven','','Arcata','Humboldt','CA','','','','');
INSERT INTO location VALUES (38,'Farallon Islands','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (39,'Filoli','','Meno Park','San Mateo','CA','','NAD-27','37.460963','122.292952');
INSERT INTO location VALUES (40,'Foster City Radio Tower','','Foster City','San Mateo','CA','','','','');
INSERT INTO location VALUES (41,'Golden Gate Park','http://www.nps.gov/goga/','San Francisco','San Francisco','CA','','mapblast','37.785718','122.42142');
INSERT INTO location VALUES (42,'Grant Ranch County Park','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (43,'Hawk Hill','http://www.ggro.org/','Sausalito','Marin','CA','','WGS 84','37.83051','122.47981');
INSERT INTO location VALUES (44,'Haystack Reservoir','http://www.recreation.gov/detail.cfm?ID=1145','Madras','Jefferson','OR','','Unknown','44.0586','121.3142');
INSERT INTO location VALUES (45,'Henry Coe State Park','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (46,'House of Ted','','Palo Alto','Santa Clara','CA','Our friend Pat introduced us to his friend Ted in Palo Alto. Ted has a lovely wooded yard with bird feeders. He attracts an interesting combination of birds I don\'t think of as backyard birds.','','','');
INSERT INTO location VALUES (47,'Humboldt County','','Arcata','Humboldt','CA','','','','');
INSERT INTO location VALUES (48,'Lake Merced','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (49,'Las Galinas Sewage Ponds','','San Rafael','Marin','CA','','','','');
INSERT INTO location VALUES (50,'Lithia Park','','Ashland','Jefferson','OR','','NAD-27','42.187581','122.68575');
INSERT INTO location VALUES (51,'Los Alamitos Water Recharge Pond','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (52,'Lower Klamath NWR','http://www.klamathnwr.org/lowerklamath.html','Tulelake','Siskiyou','CA','','mapblast','41.954152','121.474804');
INSERT INTO location VALUES (53,'Magic Brush Pile','','San Francisco','San Francisco','CA','Well, this is what Steve and Bob called it!','','','');
INSERT INTO location VALUES (54,'Malheur NWR','','Burns','Harney','OR','','','','');
INSERT INTO location VALUES (55,'Marin County','','Marin','Marin','CA','denotes birds seen while driving the roads of Marin County.','','','');
INSERT INTO location VALUES (56,'McClellan Ranch','http://www.cupertino.org/update/rec/facility.htm','Cupertino','Santa Clara','CA','the home of the Santa Clara Valley Audubon Society','','','');
INSERT INTO location VALUES (57,'Merced County','','Los Banos','Merced','CA','','','','');
INSERT INTO location VALUES (58,'Merced NWR','http://www.gorp.com/gorp/resource/us_nwr/ca_merce.htm','Merced','Merced','CA','','mapblast','37.296274','120.484357');
INSERT INTO location VALUES (59,'Monte Bello Open Space Preserve','http://www.openspace.org/MBELLO.html','Saratoga','Santa Clara','CA','','','','');
INSERT INTO location VALUES (60,'Monterey Bay','http://www.shearwaterjourneys.com/','Monterey','Monterey','CA','This location denotes pelagic trips out of Monterey Bay, especially with Debra Shearwater.','mapblast','36.60135','121.88176');
INSERT INTO location VALUES (61,'Morro Bay','http://www.morro-bay.net','Morro Bay','San Luis Obispo','CA','includes Morro Bay estuary, Montana de Oro state park, San Simeon Hearst Memorial beach, etc. The latitude and longitude coordinates given are for our rental house in Baywood Park','NAD-27','35.331817','120.840568');
INSERT INTO location VALUES (62,'Moss Landing State Beach','','Moss Landing','Santa Cruz','CA','','','','');
INSERT INTO location VALUES (63,'Mount Hamilton','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (64,'Nortel Networks','','Santa Clara','Santa Clara','CA','Mary\'s office, located right next to Great America','NAD-27','37.348709','121.952358');
INSERT INTO location VALUES (65,'Ocean Beach','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (66,'Oka Ponds','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (67,'Olompali State Park','','Novato','Marin','CA','','','','');
INSERT INTO location VALUES (68,'Palo Alto Duck Pond','http://www.xymox.palo-alto.ca.us/av/baylands.html','Palo Alto','Santa Clara','CA','our second most visited site; location of bill\'s first birdwalk with Steve Shunk.','mapblast','37.461','122.115');
INSERT INTO location VALUES (69,'Panoche Valley','http://www.ca.blm.gov/hollister/panoche_tumeys.html','Panoche','San Benito','CA','','mapblast','36.596944','120.8325');
INSERT INTO location VALUES (70,'Parcourse Marsh','','Mountain View','Santa Clara','CA','','','','');
INSERT INTO location VALUES (71,'Patricks Point State Park','http://www.parks.ca.gov/allpages/default.asp?page_id=417','Trinidad','Humboldt','CA','','NAD-27','37.478518','122.139991');
INSERT INTO location VALUES (72,'Pescadero Marsh','http://parks.ca.gov/central/bayarea/psb227.htm','Pescadero','San Mateo','CA','','Unknown','37.2143','122.328');
INSERT INTO location VALUES (73,'Philadelphia','','Philadelphia','Philadelphia','PA','','','','');
INSERT INTO location VALUES (74,'McAllen','','McAllen','Hidalgo','TX','','','','');
INSERT INTO location VALUES (131,'Phoenecian Resort','http://www.thephoenician.com','Phoenix','Maricopa','AZ','','mapblast','33.502103','111.951902');
INSERT INTO location VALUES (75,'Picchetti Ranch','http://www.openspace.org/preserves/picchetti_ranch/picchetti_ranch.html','Los Altos','Santa Clara','CA','','','','');
INSERT INTO location VALUES (76,'Pigeon Point','http://www.pigeonpointlighthouse.org/index_00.html','Pescadero','San Mateo','CA','','mapblast','37.18625','122.396556');
INSERT INTO location VALUES (77,'Pikes Peak','http://www.state.ia.us/parks/pikepeak.htm','McGregor','Clayton','IA','','Unknown','43.0056','91.2139');
INSERT INTO location VALUES (78,'Pillar Point','http://www.smharbor.com/pillarpoint/','El Granada','San Mateo','CA','','mapblast','37.509667','122.466581');
INSERT INTO location VALUES (79,'Point Pinos','','Monterey','Monterey','CA','','','','');
INSERT INTO location VALUES (80,'Point Reyes National Seashore','http://www.nps.gov/pore/','Point Reyes','Marin','CA','','Unknown','38.0849','122.7928');
INSERT INTO location VALUES (81,'Portola Redwoods State Park','','Portola','Santa Clara','CA','','','','');
INSERT INTO location VALUES (82,'Prairie Creek Redwoods State Park','http://www.parks.ca.gov/allpages/default.asp?page_id=415','Orick','Humboldt','CA','','','','');
INSERT INTO location VALUES (83,'Prairie du Chien','http://www.prairieduchien.org/','Prairie du Chien','Crawford','WI','','Unknown','43.0613','91.0624');
INSERT INTO location VALUES (84,'Princeton Harbor','','Princeton','San Mateo','CA','','','','');
INSERT INTO location VALUES (85,'Rancho San Antonio','http://www.openspace.org/RANCHO.html','Cupertino','Santa Clara','CA','','','','');
INSERT INTO location VALUES (86,'Rancho Santa Ana Botanic Gardens','','Claremont','Los Angeles','CA','Near Ran and Laura\'s house','','','');
INSERT INTO location VALUES (87,'Reactivity','http://www.reactivity.com/','Belmont','San Mateo','CA','','NAD-27','37.525241','122.266897');
INSERT INTO location VALUES (88,'Redwood Creek Horse Trail','','Orick','Humboldt','CA','','','','');
INSERT INTO location VALUES (89,'Rohnert Park','','Rohnert Park','Sonoma','CA','','','','');
INSERT INTO location VALUES (90,'Russian Ridge Open Space Preserve','http://www.openspace.org/RRIDGE.html','Saratoga','Santa Cruz','CA','','','','');
INSERT INTO location VALUES (91,'Sacramento NWR','http://www.r1.fws.gov/sacnwrc/','Sacramento','Glenn','CA','','mapblast','39.371453','122.181558');
INSERT INTO location VALUES (92,'Salton Sea','','Salton City','Imperial','CA','','','','');
INSERT INTO location VALUES (93,'San Antonio Valley','','Larwrence','Alameda','CA','','','','');
INSERT INTO location VALUES (94,'San Diego','','San Diego','San Diego','CA','','','','');
INSERT INTO location VALUES (95,'San Francisco','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (96,'San Francisco Zoo','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (97,'San Gregorio State Beach','','Pescadero','San Mateo','CA','','','','');
INSERT INTO location VALUES (98,'San Luis NWR','http://sanluis.fws.gov/','Los Banos','Merced','CA','','','','');
INSERT INTO location VALUES (99,'San Mateo County','','San Mateo','San Mateo','CA','A catch-all location for birds seen on the road in San Mateo County','','','');
INSERT INTO location VALUES (100,'Santa Clara County','','Santa Clara','Santa Clara','CA','','','','');
INSERT INTO location VALUES (101,'Santa Cruz','','Santa Cruz','Santa Cruz','CA','','','','');
INSERT INTO location VALUES (102,'Saratoga Parks','http://www.hakone.com/about/index.html','Saratoga','Santa Clara','CA','includes Hakone Gardens and Saratoga Wildwood Park','','','');
INSERT INTO location VALUES (103,'Schollenberger Park','','Petaluma','Sonoma','CA','','WGS 84','38.2308','122.59724');
INSERT INTO location VALUES (104,'Siskiyou County','','Yreka','Siskiyou','CA','','','','');
INSERT INTO location VALUES (105,'Skyline Ridge Open Space Preserve','http://www.openspace.org/SKYLINE.html','Saratoga','Santa Clara','CA','features the lovely David C. Daniels Nature Center and accompanying pond.','','','');
INSERT INTO location VALUES (106,'Sonoma County','','','Sonoma','CA','','','','');
INSERT INTO location VALUES (107,'Southwest Wisconsin','','Prairie du Chien','Crawford','WI','','','','');
INSERT INTO location VALUES (108,'St Joseph Open Space Preserve','http://www.openspace.org/STJOE.html','Saratoga','Santa Clara','CA','Probably you should park in the Lexington Reservoir parking lot, which costs four dollars.','NAD27','37.20012','121.98594');
INSERT INTO location VALUES (109,'Stanford University','','Stanford','Santa Clara','CA','Stanford lands include several different birding areas -- the hills around the radio telescope, the Stanford Mausoleum, and Lake Lagunita (mostly in winter)','mapblast','37.42405','122.164887');
INSERT INTO location VALUES (110,'Starbucks Pond','','Belmont','San Mateo','CA','Right behind Starbucks in the strip mall at Holly and Shoreway Road, near San Carlos airport','NAD-27','37.523289','122.251861');
INSERT INTO location VALUES (111,'State and Speckles Pond','http://www.stanford.edu/~kendric/birds/PondMaps/Alviso3.html','Alviso','Santa Clara','CA','','WGS 84','37.43268','121.96648');
INSERT INTO location VALUES (112,'Stevens Creek County Park','http://www.parkhere.org/prkpages/stcrk.htm','Cupertino','Santa Clara','CA','','NAD-27','37.311367','122.068432');
INSERT INTO location VALUES (113,'Stowe Lake','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (114,'Sunnyvale Baylands','http://www.ci.sunnyvale.ca.us/baylands/','Sunnyvale','Santa Clara','CA','','WGS 84','37.401098','121.9933');
INSERT INTO location VALUES (115,'Sunnyvale Water Treatment Plant','','Sunnyvale','Santa Clara','CA','','mapblast','37.41982','122.016779');
INSERT INTO location VALUES (116,'Sutro Baths','','San Francisco','San Francisco','CA','','','','');
INSERT INTO location VALUES (117,'Table Rock','','Medford','Jackson','OR','','','','');
INSERT INTO location VALUES (118,'Touvelle State Park','http://www.oregonstateparks.org/park_106.php','Medford','Jackson','OR','','Unknown','42.1843','122.5624');
INSERT INTO location VALUES (119,'Trinidad Harbor','','Trinidad','Humboldt','CA','','','','');
INSERT INTO location VALUES (120,'Trinidad State Beach','http://www.northcoast.com/~rras/hotspot2.htm','Trinidad','Humboldt','CA','','','','');
INSERT INTO location VALUES (121,'Ulistac Natural Area','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (122,'University Lutheran Church','http://www.stanford.edu/group/LSM/','Palo Alto','Santa Clara','CA','','NAD-27','37.418895','122.15533');
INSERT INTO location VALUES (123,'University of Wisconsin Arboretum','','Madison','Dane','WI','','','','');
INSERT INTO location VALUES (124,'Unknown','','Unknown','Unknown','CA','','','','');
INSERT INTO location VALUES (125,'Upper Mississippi NWR','','Prairie Du Chien','Crawford','WI','','','','');
INSERT INTO location VALUES (126,'Uvas Canyon Reservoir','','San Jose','Santa Clara','CA','','','','');
INSERT INTO location VALUES (127,'Vasona Creek','http://claraweb.co.santa-clara.ca.us/parks/prkpages/vasndch.htm','Los Gatos','Santa Clara','CA','','mapblast','37.243202','121.968783');
INSERT INTO location VALUES (128,'Wellfleet Bay','http://www.wellfleetbay.org/default.htm','South Wellfleet','Barnstable','MA','','Unknown','41.9196','69.9971');
INSERT INTO location VALUES (129,'Woodbridge Ecological Preserve','http://www.sacbee.com/ourtown/diversions/wildlife_view.html','Lodi','San Joaquin','CA','A piece of land owned by the Nature Conservancy.','mapblast','38.12325','121.294424');
INSERT INTO location VALUES (130,'Yosemite','','Yosemite National Park','Mono','CA','','','','');
INSERT INTO location VALUES (132,'Leakey','','Leaky','Real','TX','','','','');
INSERT INTO location VALUES (133,'Brownsville','','Brownsville','Cameron','TX','','','','');
INSERT INTO location VALUES (134,'Port Aransas','','Port Aransas','Neuces','TX','','','','');
INSERT INTO location VALUES (135,'Laredo','','Laredo','Webb','TX','','','','');
INSERT INTO location VALUES (136,'Corpus Christi','','Corpus Christi','Neuces','TX','','','','');
INSERT INTO location VALUES (137,'Palmetto State Park','http://www.tpwd.state.tx.us/park/palmetto/','San Antonio','Gonzales','TX','','','','');
