INSERT INTO state VALUES (1,'Alabama','AL','');
INSERT INTO state VALUES (2,'Alaska','AK','');
INSERT INTO state VALUES (3,'Arizona','AZ','');
INSERT INTO state VALUES (4,'Arkansas','AR','');
INSERT INTO state VALUES (5,'California','CA','');
INSERT INTO state VALUES (6,'Colorado','CO','');
INSERT INTO state VALUES (7,'Connecticut','CT','');
INSERT INTO state VALUES (8,'Delaware','DE','');
INSERT INTO state VALUES (9,'Florida','FL','');
INSERT INTO state VALUES (10,'Georgia','GA','');
INSERT INTO state VALUES (11,'Hawaii','HI','');
INSERT INTO state VALUES (12,'Idaho','ID','');
INSERT INTO state VALUES (13,'Illinois','IL','');
INSERT INTO state VALUES (14,'Indiana','IN','');
INSERT INTO state VALUES (15,'Iowa','IA','');
INSERT INTO state VALUES (16,'Kansas','KS','');
INSERT INTO state VALUES (17,'Kentucky','KY','');
INSERT INTO state VALUES (18,'Lousiana','LA','');
INSERT INTO state VALUES (19,'Maine','ME','');
INSERT INTO state VALUES (20,'Maryland','MD','');
INSERT INTO state VALUES (21,'Massachusetts','MA','');
INSERT INTO state VALUES (22,'Michigan','MI','');
INSERT INTO state VALUES (23,'Minnesota','MN','');
INSERT INTO state VALUES (24,'Mississippi','MS','');
INSERT INTO state VALUES (25,'Missouri','MO','');
INSERT INTO state VALUES (26,'Montana','MT','');
INSERT INTO state VALUES (27,'Nebraska','NE','');
INSERT INTO state VALUES (28,'Nevada','NV','');
INSERT INTO state VALUES (29,'New Hampshire','NH','');
INSERT INTO state VALUES (30,'New Jersey','NJ','');
INSERT INTO state VALUES (31,'New Mexico','NM','');
INSERT INTO state VALUES (32,'New York','NY','');
INSERT INTO state VALUES (33,'North Carolina','NC','');
INSERT INTO state VALUES (34,'North Dakota','ND','');
INSERT INTO state VALUES (35,'Ohio','OH','');
INSERT INTO state VALUES (36,'Oklahoma','OK','');
INSERT INTO state VALUES (37,'Oregon','OR','');
INSERT INTO state VALUES (38,'Pennsylvania','PA','');
INSERT INTO state VALUES (39,'Rhode Island','RI','');
INSERT INTO state VALUES (40,'South Carolina','SC','');
INSERT INTO state VALUES (41,'South Dakota','SD','');
INSERT INTO state VALUES (42,'Tennessee','TN','');
INSERT INTO state VALUES (43,'Texas','TX','');
INSERT INTO state VALUES (44,'Utah','UT','');
INSERT INTO state VALUES (45,'Vermont','VT','');
INSERT INTO state VALUES (46,'Virginia','VA','');
INSERT INTO state VALUES (47,'Washington','WA','');
INSERT INTO state VALUES (48,'West Virginia','WV','');
INSERT INTO state VALUES (49,'Wisconsin','WI','');
INSERT INTO state VALUES (50,'Wyoming','WY','');
